apiVersion: v1
kind: Service
metadata:
  name: quest
  labels:
    app: quest
spec:
  ports:
    - port: 80
  selector:
    app: quest
    tier: frontend/backend
  # type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  labels:
    app: quest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quest
  labels:
    app: quest
spec:
  selector:
    matchLabels:
      app: quest
      tier: frontend/backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: quest
        tier: frontend/backend
    spec:
      containers:
      - image: node:20-alpine
        name: my-node-app
        env:
        # - name: QUEST_DB_HOST
        #   value: QUEST-mysql
        # - name: QUEST_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-pass
              key: password
        # - name: QUEST_DB_USER
          value: quest-user
        ports:
        - containerPort: 80
          name: quest
        volumeMounts:
        - name: quest-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: quest-persistent-storage
        persistentVolumeClaim:
          claimName: db-pv-claim
